name: Trivy Scan

on:
  workflow_dispatch:

jobs:
  security:
    # Sneaking past the traffic jam by targeting a specific older pool
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Install Trivy CLI Natively
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy Scan (console output)
        run: |
          trivy fs --severity HIGH,CRITICAL --format table .
